
exports.PHYSICS_INTERVAL = 50;
exports.MAX_LEN_LASER = 8;
exports.MIN_LEN_LASER = 1;
exports.BOUNDS_DIAMETER = 30;
exports.TIME_SPAWN = 2000;
exports.ACCELERATION_FACTOR = 4
exports.MAX_ACCELERATION = 3.5
exports.KILL_SCORE = 100
