
exports.PHYSICS_INTERVAL = 50;
exports.MAX_LEN_LASER = 8;
exports.MIN_LEN_LASER = 1;
exports.BOUNDS_DIAMETER = 30;
exports.TIME_SPAWN = 2000;
exports.ACCELERATION_FACTOR = 2
exports.MAX_ACCELERATION = 5
exports.FRICTION_FACTOR = 1
